
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-09
owner: ucsb-cs156-f24
repo_name: team01-f24-09
pull_requests: [{"author":{"id":"U_kgDOBtFE9g","is_bot":false,"login":"TomShangguan","name":""},"headRefName":"tom-DiningMenuItem-Task10","number":50,"title":"Tom dining menu item task10","url":"https://github.com/ucsb-cs156-f24/team01-f24-09/pull/50"},{"author":{"id":"U_kgDOB0zhkA","is_bot":false,"login":"alecsong222","name":"Alec Song"},"headRefName":"Alec-HelpReqTable","number":48,"title":"Alec - Created HelpRequests Table","url":"https://github.com/ucsb-cs156-f24/team01-f24-09/pull/48"}]
