
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-09
owner: ucsb-cs156-f24
repo_name: team01-f24-09
pull_requests: [{"author":{"id":"U_kgDOBt0KgA","is_bot":false,"login":"azhe12345","name":""},"headRefName":"Hongtao-RQ","number":61,"title":"Hongtao rq","url":"https://github.com/ucsb-cs156-f24/team01-f24-09/pull/61"},{"author":{"id":"U_kgDOBtFGRA","is_bot":false,"login":"neil-roy","name":""},"headRefName":"MenuItemReview-Finished","number":60,"title":"Menu item review finished","url":"https://github.com/ucsb-cs156-f24/team01-f24-09/pull/60"}]
