
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/team01-f24-09
owner: ucsb-cs156-f24
repo_name: team01-f24-09
pull_requests: [{"author":{"id":"U_kgDOB2_DTg","is_bot":false,"login":"elijahelephant","name":"Elijah Williams"},"headRefName":"14-orgController","number":47,"title":"15 UCSB org controller","url":"https://github.com/ucsb-cs156-f24/team01-f24-09/pull/47"},{"author":{"id":"U_kgDOBtFE9g","is_bot":false,"login":"TomShangguan","name":""},"headRefName":"tom-UCSBDiningCommonsMenuItemController-Get-Post","number":46,"title":"Tom ucsb dining commons menu item controller get post","url":"https://github.com/ucsb-cs156-f24/team01-f24-09/pull/46"},{"author":{"id":"U_kgDOBtFE9g","is_bot":false,"login":"TomShangguan","name":""},"headRefName":"tom-UCSBDiningCommonsMenuItem-create-db","number":45,"title":"tom-UCSBDiningCommonsMenuItem-create-db","url":"https://github.com/ucsb-cs156-f24/team01-f24-09/pull/45"}]
